# Chapter 6

## A look at Python objects

### int

In [1]:
n = 5
type (n)

int

In [ ]:
n.numerator

5

In [ ]:
n.bit_length()  # 表示整数 n 的绝对值所需的最小二进制位数

3

In [4]:
n + n

10

In [ ]:
2 ** n   # 2^n 次方

32

In [ ]:
n.__sizeof__()     
# 获取对象 n 本身在内存中占用的字节数（不包括其引用的子对象） 的方法
# 28 (在 64 位系统上)

28

### list

In [8]:
l = [1, 2, 3, 4]
type(l)

list

In [9]:
l[0]

1

In [10]:
l.append(10)
l+l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [11]:
2 * l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [12]:
sum(l)

20

In [14]:
l.__sizeof__()

104

### ndarray

In [15]:
import numpy as np
a = np.arange(16).reshape((4,4))

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


\begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11 \\
12 & 13 & 14 & 15
\end{bmatrix}

In [16]:
type(a)

numpy.ndarray

In [17]:
a.nbytes

128

In [18]:
a.sum()

np.int64(120)

In [ ]:
a.cumsum(axis = 0)  
# 沿第 0 轴（行方向）做累积和 → 按列从上到下累加

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

# `a.cumsum(axis=0)` 计算过程详解

## 1. 原始矩阵

设数组 `a` 由 `np.arange(16).reshape(4, 4)` 生成：

$$
a = 
\begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11 \\
12 & 13 & 14 & 15
\end{bmatrix}
$$

## 2. `axis=0` 的含义

- `axis=0` 表示 **沿第 0 轴（行方向）进行累积**
- 即：**对每一列，从上到下逐行累加**
- 每一列独立计算前缀和（cumulative sum）

## 3. 逐元素计算过程

我们按行逐步计算累积和。

### 第 0 行（初始值，无累加）

- 结果第 0 行 = 原始第 0 行  
  $$
  \text{row}_0^{\text{out}} = [0,\ 1,\ 2,\ 3]
  $$

### 第 1 行（累加前两行）

- 第 0 列：$ 0 + 4 = 4 $
- 第 1 列：$ 1 + 5 = 6 $
- 第 2 列：$ 2 + 6 = 8 $
- 第 3 列：$ 3 + 7 = 10 $

$$
\text{row}_1^{\text{out}} = [4,\ 6,\ 8,\ 10]
$$

### 第 2 行（累加前三行）

- 第 0 列：$ 0 + 4 + 8 = 12 $
- 第 1 列：$ 1 + 5 + 9 = 15 $
- 第 2 列：$ 2 + 6 + 10 = 18 $
- 第 3 列：$ 3 + 7 + 11 = 21 $

$$
\text{row}_2^{\text{out}} = [12,\ 15,\ 18,\ 21]
$$

### 第 3 行（累加全部四行）

- 第 0 列：$ 0 + 4 + 8 + 12 = 24 $
- 第 1 列：$ 1 + 5 + 9 + 13 = 28 $
- 第 2 列：$ 2 + 6 + 10 + 14 = 32 $
- 第 3 列：$ 3 + 7 + 11 + 15 = 36 $

$$
\text{row}_3^{\text{out}} = [24,\ 28,\ 32,\ 36]
$$

## 4. 最终结果矩阵

将各行输出组合成完整矩阵：

$$
a.\text{cumsum}(axis=0) = 
\begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 6 & 8 & 10 \\
12 & 15 & 18 & 21 \\
24 & 28 & 32 & 36
\end{bmatrix}
$$


In [20]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [21]:
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [22]:
sum(a)

array([24, 28, 32, 36])

In [23]:
np.sum(a)

np.int64(120)

In [25]:
a.__sizeof__()

128

### DataFrame

In [26]:
import pandas as pd

df = pd.DataFrame(a, columns = list('abcd'))

type(df)

pandas.core.frame.DataFrame

In [27]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [28]:
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [29]:
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [30]:
df + df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [31]:
df * 2

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [32]:
np.sum(df)

c:\Users\bihui\miniconda3\Lib\site-packages\numpy\_core\fromnumeric.py:81: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


a    24
b    28
c    32
d    36
dtype: int64

In [33]:
df.__sizeof__()

260

## Basics of Python classes

### FinancialInstrument

In [ ]:
class FinancialInstrument(object):
    pass
fi = FinancialInstrument()

type(fi)

__main__.FinancialInstrument

↑ Python 中一个 类（class）的完整限定名称（fully qualified name）

In [35]:
fi

In [37]:
fi.price = 100

fi.price

100

In [38]:
class FinancialInstrument(object):
   author = 'Susan Bi' 
   def __init__(self, symbol, price): 
     self.symbol = symbol 
     self.price = price

FinancialInstrument.author

'Susan Bi'

In [40]:
aapl = FinancialInstrument('AAPL', 100)

aapl.symbol

'AAPL'

In [41]:
aapl.author

'Susan Bi'

In [42]:
aapl.price = 105

aapl.price

105

<br>

In [43]:
class FinancialInstrument(FinancialInstrument): 
   def get_price(self): 
     return self.price 
   def set_price(self, price): 
     self.price = price

fi = FinancialInstrument('AAPL', 100)

fi.get_price()

100

In [ ]:
fi.set_price(105)

fi.get_price()   # set_price update the price before

105

In [47]:
fi.price

105

<br>

In [48]:
class FinancialInstrument(object):
   def __init__(self, symbol, price):
     self.symbol = symbol
     self.__price = price 
   def get_price(self):
     return self.__price
   def set_price(self, price):
     self.__price = price

fi = FinancialInstrument('AAPL', 100)

fi.get_price()

100

In [50]:
fi._FinancialInstrument__price

100

In [ ]:
fi._FinancialInstrument__price = 105
fi.set_price(100) # set price back to its original value

### PortfolioPosition

In [53]:
class PortfolioPosition(object):
   def __init__(self, financial_instrument, position_size):
     self.position = financial_instrument 
     self.__position_size = position_size 
   def get_position_size(self):
     return self.__position_size
   def update_position_size(self, position_size):
     self.__position_size = position_size
   def get_position_value(self):
     return self.__position_size * \
            self.position.get_price()

pp = PortfolioPosition(fi, 10)
pp.get_position_size()

10

In [54]:
pp.get_position_value()

1000

In [55]:
pp.position.get_price()

100

In [57]:
pp.position.set_price(105)
pp.get_position_value()

1050

## Python Data model

### special method __init__:

In [ ]:
class Vector(object):
   def __init__(self, x=0, y=0, z=0): 
     self.x = x 
     self.y = y 
     self.z = z

v = Vector(1, 2, 3)

v

### special method __repr__:

In [59]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
    
v = Vector(1, 2, 3)

print(v)

Vector(1, 2, 3)


### special methods __abs__ and __bool__:

In [ ]:
class Vector(Vector):
   def __abs__(self):
     return (self.x ** 2 + self.y ** 2 +
             self.z ** 2) ** 0.5 
   
   def __bool__(self):
     return bool(abs(self))
   
v = Vector(1, 2, -1)

abs(v)  # = sqrt(1^2 + 3^2 + (-1)^2)

2.449489742783178

In [ ]:
bool(v)   # True的意思：非零向量

True

In [63]:
v = Vector()

v

Vector(0, 0, 0)

In [64]:
abs(v)

0.0

In [65]:
bool(v)

False

### special method __len__ and __getitem__

In [66]:
class Vector(Vector):
   def __len__(self):
     return 3 
   def __getitem__(self, i):
     if i in [0, -3]: return self.x
     elif i in [1, -2]: return self.y
     elif i in [2, -1]: return self.z
     else: raise IndexError('Index out of range.')

v = Vector(1, 2, 3)

len(v)

3

In [67]:
v[0]

1

In [68]:
v[-2]

2

In [69]:
v[3]

IndexError: Index out of range.

### special method __iter__

In [71]:
class Vector(Vector):
   def __iter__(self):
     for i in range(len(self)):
        yield self[i]

v = Vector(1, 2, 3)

for i in range(3):
   print(v[i])

1
2
3


In [72]:
for coordinate in v:
    print(coordinate)

1
2
3


## The Vector Class

In [ ]:
class Vector(object):
   def __init__(self, x=0, y=0, z=0):
     self.x = x
     self.y = y
     self.z = z
   
   def __repr__(self):
     return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
   
   def __abs__(self):
     return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
 
   def __bool__(self):
     return bool(abs(self))
 
   def __add__(self, other):
     x = self.x + other.x
     y = self.y + other.y
     z = self.z + other.z
     return Vector(x, y, z)
 
   def __mul__(self, scalar):
     return Vector(self.x * scalar,
                   self.y * scalar,
                   self.z * scalar)
 
   def __len__(self):
     return 3
 
   def __getitem__(self, i):
     if i in [0, -3]: return self.x
     elif i in [1, -2]: return self.y
     elif i in [2, -1]: return self.z
     else: raise IndexError('Index out of range.')
 
   def __iter__(self):
     for i in range(len(self)):
       yield self[i]